### ISSUE TITLE
Comentarios

### ISSUE THREAD

**Issue by CarlosRubioTNM** [RayadoxAV/Practica1NephBanned#1]
Muy bien, jóvenes. Me gustó el diseño que usaron.

Les encargo las siguientes correcciones:

- En la sección de intereses, tengan consistencia en cuanto al uso de mayúsculas y minúsculas, elijan una y aplíquenlo en los intereses de los 4.
- Agreguen donde les parezca mejor un párrafo inventado sobre la historia de su empresa.
- Le faltaron emojis al perfil de Raymundo, les encargo que pongan otros 5.

Espero su respuesta.

**Comment by armandoreyr** [comment]
Se realizaron los cambios.

**Comment by armandoreyr** [comment]
@CarlosRubioTNM

**Comment by CarlosRubioTNM** [comment]
Ya está revisado. Buen trabajo, jóvenes. Cierro el issue. 👍
